services:

  db:
    image: redis:alpine
    container_name: db-service
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    networks:
      - app-network

  web:
    build: .
    depends_on:
      - db
    environment:
      REDIS_HOST: db-service
    ports:
      - "${PORT}:5000"
    networks:
      - app-network

volumes:
  redis-data:
    external: true

networks:
  app-network:
    external: true