pipeline {
    agent any

    triggers {
        githubPush()
    }

    environment {
        IMAGE = 'samia999/counter-app'
        DOCKERHUB = credentials('dockerhub-creds')
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build & Tests unitaires') {
            agent {
                docker {
                    image 'python:3.12-slim'
                    args '-e HOME=/tmp'
                    reuseNode true
                }
            }

            steps {
                dir('partie-b/app') {
                    sh 'pip install --no-cache-dir -r requirements.txt'
                    sh 'python -m pytest -v'
                }
            }
        }

        stage('Build image Docker') {
            steps {
                dir('partie-b/app') {
                    sh 'docker build -t $IMAGE:$BUILD_NUMBER -t $IMAGE:latest .'
                }
            }
        }

        stage('Push Docker Hub') {
            when {
                branch 'main'
            }

            steps {
                sh 'echo $DOCKERHUB_PSW | docker login -u $DOCKERHUB_USR --password-stdin'
                sh 'docker push $IMAGE:$BUILD_NUMBER'
                sh 'docker push $IMAGE:latest'
            }
        }
    }

    post {
        always {
            sh 'docker logout || true'
        }
    }
}